# Generated by Django 5.2.7 on 2025-10-10 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อห้องประชุม')),
                ('capacity', models.PositiveIntegerField(verbose_name='ความจุ (คน)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='ที่ตั้ง (อาคาร/ชั้น)')),
                ('equipment', models.TextField(blank=True, verbose_name='รายการอุปกรณ์ (แต่ละรายการขึ้นบรรทัดใหม่)')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้อการประชุม')),
                ('start_time', models.DateTimeField(verbose_name='เวลาเริ่มต้น')),
                ('end_time', models.DateTimeField(verbose_name='เวลาสิ้นสุด')),
                ('status', models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ถูกปฏิเสธ')], default='PENDING', max_length=10, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้จอง')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.room', verbose_name='ห้องประชุม')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
