# Generated by Django 5.2.7 on 2025-10-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='recurring',
            field=models.CharField(choices=[('NONE', 'ไม่มี'), ('DAILY', 'ทุกวัน'), ('WEEKLY', 'ทุกสัปดาห์'), ('MONTHLY', 'ทุกเดือน')], default='NONE', max_length=10, verbose_name='การจองซ้ำ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ถูกปฏิเสธ')], default='APPROVED', max_length=10, verbose_name='สถานะ'),
        ),
    ]
