# Generated by Django 5.2.7 on 2025-10-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='recurring',
        ),
        migrations.AlterField(
            model_name='room',
            name='equipment',
            field=models.TextField(blank=True, verbose_name='อุปกรณ์ที่พร้อมใช้งาน'),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='อาคาร / สถานที่'),
        ),
    ]
