# Generated by Django 5.2.7 on 2025-10-14 04:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_created_at_remove_booking_recurring_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่ออุปกรณ์')),
            ],
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-start_time']},
        ),
        migrations.RemoveField(
            model_name='room',
            name='equipment',
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_notes',
            field=models.TextField(blank=True, verbose_name='เพิ่มเติม'),
        ),
        migrations.AddField(
            model_name='booking',
            name='chairman',
            field=models.CharField(blank=True, max_length=255, verbose_name='ประธานการประชุม'),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name='แผนก'),
        ),
        migrations.AddField(
            model_name='booking',
            name='participant_count',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวนผู้เข้าร่วม'),
        ),
        migrations.AddField(
            model_name='booking',
            name='requester_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทรติดต่อ'),
        ),
        migrations.AddField(
            model_name='room',
            name='equipment_in_room',
            field=models.TextField(blank=True, verbose_name='อุปกรณ์ประจำห้อง'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขอใช้'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ถูกปฏิเสธ')], default='PENDING', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(max_length=255, verbose_name='วาระการประชุม'),
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment_needed',
            field=models.ManyToManyField(blank=True, to='booking.equipment', verbose_name='อุปกรณ์ที่ต้องใช้'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/', verbose_name='รูปโปรไฟล์')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
