# Generated by Django 5.2.7 on 2025-10-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_equipment_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='equipment_in_room',
            field=models.TextField(blank=True, verbose_name='อุปกรณ์ที่พร้อมใช้งาน'),
        ),
    ]
