# Generated by Django 5.2.7 on 2025-10-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_room_equipment_in_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='equipment_needed',
        ),
        migrations.AlterField(
            model_name='booking',
            name='additional_notes',
            field=models.TextField(blank=True, verbose_name='อุปกรณ์เสริมที่ต้องการเพิ่มเติม / หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ถูกปฏิเสธ'), ('CANCELLED', 'ยกเลิกแล้ว')], default='PENDING', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
