# Generated by Django 5.2.7 on 2025-10-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_equipment_needed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='department',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='requester_phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/', verbose_name='ไฟล์แนบ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='additional_notes',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
    ]
