# Generated by Django 5.2.7 on 2025-10-16 02:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_booking_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='meetings_attending', to=settings.AUTH_USER_MODEL, verbose_name='รายชื่อผู้เข้าร่วม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participant_count',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวนผู้เข้าร่วม (โดยประมาณ)'),
        ),
    ]
