# Generated by Django 5.2.7 on 2025-10-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_participants_alter_booking_participant_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.CharField(blank=True, max_length=100, verbose_name='อาคาร'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.CharField(blank=True, max_length=50, verbose_name='ชั้น'),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='โซน / สถานที่'),
        ),
    ]
