# Generated by Django 5.2.7 on 2025-10-16 08:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_requests',
            field=models.TextField(blank=True, verbose_name='คำขออุปกรณ์ / บริการเพิ่มเติม'),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='แผนก'),
        ),
        migrations.AlterField(
            model_name='room',
            name='equipment_in_room',
            field=models.TextField(blank=True, verbose_name='อุปกรณ์ที่มีในห้อง (แต่ละรายการขึ้นบรรทัดใหม่)'),
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('LOGIN', 'เข้าสู่ระบบ'), ('LOGOUT', 'ออกจากระบบ')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ประวัติการเข้าสู่ระบบ',
                'ordering': ['-timestamp'],
            },
        ),
    ]
