# Generated by Django 5.2.7 on 2025-10-20 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_room_room_image_alter_room_building_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-start_time'], 'verbose_name': 'การจอง', 'verbose_name_plural': 'การจองทั้งหมด'},
        ),
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'ประวัติการเข้าสู่ระบบ', 'verbose_name_plural': 'ประวัติการเข้าสู่ระบบ'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'โปรไฟล์ผู้ใช้', 'verbose_name_plural': 'โปรไฟล์ผู้ใช้'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'ห้องประชุม', 'verbose_name_plural': 'ห้องประชุม'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_image',
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='อัปเดตเมื่อ'),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='additional_notes',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='additional_requests',
            field=models.TextField(blank=True, null=True, verbose_name='คำขออุปกรณ์ / บริการเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_made', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขอใช้'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='chairman',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ประธานการประชุม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='แผนก'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='img/default.jpg', upload_to='profile_pics/', verbose_name='รูปโปรไฟล์'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='อาคาร'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='ความจุ (คน)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='equipment_in_room',
            field=models.TextField(blank=True, null=True, verbose_name='อุปกรณ์ที่มีในห้อง (แต่ละรายการขึ้นบรรทัดใหม่)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ชั้น'),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='โซน / สถานที่'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='ชื่อห้องประชุม'),
        ),
    ]
