# Generated by Django 5.2.7 on 2025-10-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_booking_options_alter_loginhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='รูปภาพ 1'),
        ),
        migrations.AddField(
            model_name='room',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='รูปภาพ 2'),
        ),
        migrations.AddField(
            model_name='room',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='รูปภาพ 3'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='อาคาร'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='equipment_in_room',
            field=models.TextField(blank=True, default='', verbose_name='อุปกรณ์ที่มีในห้อง (แต่ละรายการขึ้นบรรทัดใหม่)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ชั้น'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, default=' ', max_length=255, verbose_name='โซน / สถานที่'),
            preserve_default=False,
        ),
    ]
