# Generated by Django 5.2.7 on 2025-10-22 09:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_booking_options_alter_loginhistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-start_time'], 'verbose_name': 'การจอง', 'verbose_name_plural': 'รายการจองทั้งหมด'},
        ),
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'ประวัติการเข้าใช้งาน', 'verbose_name_plural': 'ประวัติการเข้าใช้งาน'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'ข้อมูลผู้ใช้เพิ่มเติม', 'verbose_name_plural': 'ข้อมูลผู้ใช้เพิ่มเติม'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building', 'floor', 'name'], 'verbose_name': 'ห้องประชุม', 'verbose_name_plural': 'ห้องประชุม'},
        ),
        migrations.AddField(
            model_name='booking',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='แผนกผู้จอง'),
        ),
        migrations.AddField(
            model_name='booking',
            name='presentation_file',
            field=models.FileField(blank=True, help_text='ไฟล์ที่ต้องการเปิดขึ้นจอ (PDF, PPT, Word, Excel)', null=True, upload_to='presentation_files/', verbose_name='ไฟล์นำเสนอ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='additional_notes',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='additional_requests',
            field=models.TextField(blank=True, help_text='เช่น กาแฟ, อุปกรณ์พิเศษ', null=True, verbose_name='คำขอเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='attachment',
            field=models.FileField(blank=True, help_text='เอกสารอื่นๆ ที่เกี่ยวข้อง', null=True, upload_to='booking_attachments/', verbose_name='ไฟล์แนบอื่นๆ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จอง'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='chairman',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ประธานในที่ประชุม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียด/วาระ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาสิ้นสุด'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participant_count',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวนผู้เข้าร่วม (โดยประมาณ)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_bookings', to=settings.AUTH_USER_MODEL, verbose_name='รายชื่อผู้เข้าร่วม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.room', verbose_name='ห้องประชุม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาเริ่มต้น'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ถูกปฏิเสธ'), ('CANCELLED', 'ยกเลิกแล้ว')], default='PENDING', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(max_length=200, verbose_name='หัวข้อการประชุม'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'เข้าสู่ระบบ'), ('LOGOUT', 'ออกจากระบบ')], max_length=10, verbose_name='การกระทำ'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่บันทึก'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='รูปโปรไฟล์'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='แผนก/ฝ่าย'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='อาคาร'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=1, verbose_name='ความจุ (คน)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='equipment_in_room',
            field=models.TextField(blank=True, help_text='ระบุอุปกรณ์ทีละรายการ บรรทัดละอย่าง', null=True, verbose_name='อุปกรณ์ภายในห้อง'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ชั้น'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='รูปภาพห้องประชุม'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='ชื่อห้องประชุม'),
        ),
    ]
