# Generated by Django 5.2.7 on 2025-10-23 04:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_booking_options_alter_loginhistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='external_participants',
            field=models.TextField(blank=True, help_text='สำหรับแขก หรือผู้ที่ไม่มีบัญชีในระบบ (พิมพ์ชื่อ คั่นด้วยจุลภาค หรือขึ้นบรรทัดใหม่)', null=True, verbose_name='รายชื่อผู้เข้าร่วม (ภายนอก)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_bookings', to=settings.AUTH_USER_MODEL, verbose_name='รายชื่อผู้เข้าร่วม (ในระบบ)'),
        ),
    ]
