# Generated by Django 5.2.7 on 2025-10-24 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_booking_external_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='external_participants',
        ),
    ]
