# Generated by Django 5.2.7 on 2025-10-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_remove_booking_external_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='external_participants',
            field=models.TextField(blank=True, help_text='สำหรับแขก หรือผู้ที่ไม่มีบัญชีในระบบ (พิมพ์ชื่อ คั่นด้วยจุลภาค หรือขึ้นบรรทัดใหม่)', null=True, verbose_name='รายชื่อผู้เข้าร่วม (ภายนอก)'),
        ),
    ]
