# Generated by Django 5.2.7 on 2025-10-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_alter_booking_options_alter_loginhistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image3',
        ),
    ]
