# Generated by Django 5.2.7 on 2025-10-27 04:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_remove_profile_profile_picture_remove_room_image1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่ออุปกรณ์')),
            ],
            options={
                'verbose_name': 'อุปกรณ์',
                'verbose_name_plural': 'อุปกรณ์',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-start_time'], 'verbose_name': 'การจอง', 'verbose_name_plural': 'รายการจองทั้งหมด'},
        ),
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'verbose_name': 'ห้องประชุม', 'verbose_name_plural': 'ห้องประชุม'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='department_meeting',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='room',
            name='location',
        ),
        migrations.AddField(
            model_name='booking',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='แผนกผู้จอง'),
        ),
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียด/วาระ'),
        ),
        migrations.AddField(
            model_name='booking',
            name='external_participants',
            field=models.TextField(blank=True, help_text='สำหรับแขก หรือผู้ที่ไม่มีบัญชีในระบบ (พิมพ์ชื่อ คั่นด้วยจุลภาค หรือขึ้นบรรทัดใหม่)', null=True, verbose_name='รายชื่อผู้เข้าร่วม (ภายนอก)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='presentation_file',
            field=models.FileField(blank=True, null=True, upload_to='presentation_files/', verbose_name='ไฟล์นำเสนอ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='รูปโปรไฟล์'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='รูปภาพห้องประชุม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='additional_notes',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='additional_requests',
            field=models.TextField(blank=True, null=True, verbose_name='คำขอเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='booking_attachments/%Y/%m/', verbose_name='ไฟล์แนบประกอบ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_made', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จอง'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='chairman',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ประธานในที่ประชุม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาสิ้นสุด'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participant_count',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวนผู้เข้าร่วม (ตัวเลข)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_bookings', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เข้าร่วม (จาก AD/User)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาเริ่มต้น'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(max_length=200, verbose_name='หัวข้อการประชุม'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'เข้าสู่ระบบ'), ('LOGOUT', 'ออกจากระบบ')], max_length=10, verbose_name='การกระทำ'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่บันทึก'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='แผนก/ฝ่าย'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='อาคาร'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=1, verbose_name='ความจุ (คน)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='equipment_in_room',
            field=models.TextField(blank=True, null=True, verbose_name='อุปกรณ์ภายในห้อง (อื่นๆ)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ชั้น'),
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='booking.equipment', verbose_name='อุปกรณ์ที่ต้องการ'),
        ),
    ]
