# Generated by Django 5.2.7 on 2025-10-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_equipment_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='external_participants',
        ),
        migrations.AlterField(
            model_name='booking',
            name='additional_requests',
            field=models.TextField(blank=True, null=True, verbose_name='คำขอเพิ่มเติม (เช่น กาแฟ, อุปกรณ์พิเศษ)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='presentation_file',
            field=models.FileField(blank=True, help_text='ไฟล์ที่ต้องการเปิดขึ้นจอ (PDF, PPT, Word, Excel)', null=True, upload_to='presentation_files/%Y/%m/', verbose_name='ไฟล์นำเสนอ'),
        ),
        migrations.AlterField(
            model_name='room',
            name='equipment_in_room',
            field=models.TextField(blank=True, help_text='อุปกรณ์ที่มีให้ในห้อง (เช่น โปรเจคเตอร์, ไวท์บอร์ด)', null=True, verbose_name='อุปกรณ์ภายในห้อง (อื่นๆ)'),
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
