# Generated by Django 5.2.7 on 2025-10-30 09:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_remove_booking_equipment_remove_profile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-start_time'], 'verbose_name': 'การจอง', 'verbose_name_plural': 'การจองทั้งหมด'},
        ),
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'ประวัติการเข้าสู่ระบบ', 'verbose_name_plural': 'ประวัติการเข้าสู่ระบบ'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'ห้องประชุม', 'verbose_name_plural': 'ห้องประชุม'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='department',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='description',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='presentation_file',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='booking',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='booking_attachments/%Y/%m/', verbose_name='ไฟล์เอกสาร'),
        ),
        migrations.AddField(
            model_name='booking',
            name='department_meeting',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='แผนก (สำหรับการประชุม)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='อัปเดตเมื่อ'),
        ),
        migrations.AddField(
            model_name='room',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='รูปภาพ 1'),
        ),
        migrations.AddField(
            model_name='room',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='รูปภาพ 2'),
        ),
        migrations.AddField(
            model_name='room',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='รูปภาพ 3'),
        ),
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='โซน / สถานที่'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='additional_notes',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='additional_requests',
            field=models.TextField(blank=True, null=True, verbose_name='คำขออุปกรณ์/บริการเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_made', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขอใช้'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='chairman',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ประธานการประชุม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(verbose_name='เวลาสิ้นสุด'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participant_count',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวนผู้เข้าร่วม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='meetings_attending', to=settings.AUTH_USER_MODEL, verbose_name='รายชื่อผู้เข้าร่วม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(verbose_name='เวลาเริ่มต้น'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(max_length=255, verbose_name='หัวข้อการประชุม'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'เข้าสู่ระบบ'), ('LOGOUT', 'ออกจากระบบ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='อาคาร'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='ความจุ (คน)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='equipment_in_room',
            field=models.TextField(blank=True, null=True, verbose_name='อุปกรณ์ที่มีในห้อง (แต่ละรายการขึ้นบรรทัดใหม่)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ชั้น'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='แผนก')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'โปรไฟล์ผู้ใช้',
                'verbose_name_plural': 'โปรไฟล์ผู้ใช้',
            },
        ),
    ]
