# Generated by Django 5.2.7 on 2025-10-31 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_alter_booking_options_alter_loginhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='parent_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_instances', to='booking.booking', verbose_name='รายการแม่ (ถ้ามีการจองซ้ำ)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurrence_type',
            field=models.CharField(choices=[('NONE', 'ไม่ซ้ำ'), ('WEEKLY', 'รายสัปดาห์'), ('MONTHLY', 'รายเดือน')], default='NONE', max_length=10, verbose_name='การจองซ้ำ'),
        ),
        migrations.AddField(
            model_name='booking',
            name='repeat_until',
            field=models.DateField(blank=True, null=True, verbose_name='ซ้ำจนถึงวันที่'),
        ),
    ]
