# Generated by Django 5.2.7 on 2025-11-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_remove_profile_user_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='room',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='รูปภาพ 1 (รูปหลัก)'),
        ),
        migrations.AddField(
            model_name='room',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='รูปภาพ 2'),
        ),
        migrations.AddField(
            model_name='room',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='รูปภาพ 3'),
        ),
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, help_text="เช่น 'ใกล้ฝ่ายบุคคล'", max_length=255, null=True),
        ),
    ]
