# Generated by Django 5.2.7 on 2025-11-04 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_remove_room_image1_remove_room_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='parent_booking',
            field=models.ForeignKey(blank=True, help_text='การจองนี้ เป็นส่วนหนึ่งของการจองซ้ำ (ชี้ไปที่การจองแรก)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_bookings', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurrence_rule',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
