# Generated by Django 5.2.7 on 2025-11-04 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='เลือก User ที่มีสิทธิ์อนุมัติห้องนี้ (ถ้าเว้นว่าง = Admin กลาง)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvable_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
