# Generated by Django 5.2.7 on 2025-11-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_room_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, help_text="ติ๊กออก เพื่อ 'ปิดปรับปรุง' ห้องนี้ (ห้องจะไม่แสดงในหน้าจอง)"),
        ),
    ]
