# Generated by Django 5.2.7 on 2025-11-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_room_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_active',
        ),
        migrations.AddField(
            model_name='room',
            name='is_maintenance',
            field=models.BooleanField(default=False, help_text="ติ๊กถูก [✓] เพื่อ 'ปิดปรับปรุง' ห้องนี้"),
        ),
    ]
