# Generated by Django 5.2.7 on 2025-11-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_remove_room_is_active_room_is_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='maintenance_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='สิ้นสุดปิดปรับปรุง (อัตโนมัติ)'),
        ),
        migrations.AddField(
            model_name='room',
            name='maintenance_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เริ่มปิดปรับปรุง (อัตโนมัติ)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_maintenance',
            field=models.BooleanField(default=False, help_text="ติ๊กถูก [✓] เพื่อ 'ปิดปรับปรุง' ห้องนี้", verbose_name='ปิดปรับปรุง (โหมดแมนนวล)'),
        ),
    ]
