# Generated by Django 5.2.7 on 2025-11-11 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_room_maintenance_end_room_maintenance_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='outlook_event_id',
            field=models.CharField(blank=True, help_text='ID ของ Event ที่ถูกสร้างใน Microsoft Calendar', max_length=255, null=True, verbose_name='Outlook Event ID'),
        ),
        migrations.AddField(
            model_name='room',
            name='line_notify_token',
            field=models.CharField(blank=True, help_text='โทเคนสำหรับแจ้งเตือนไปยังกลุ่ม LINE ประจำห้อง (ถ้ามี)', max_length=50, null=True, verbose_name='LINE Notify Token'),
        ),
        migrations.AddField(
            model_name='room',
            name='teams_webhook_url',
            field=models.TextField(blank=True, help_text='URL สำหรับแจ้งเตือนไปยัง Channel Teams ประจำห้อง (ถ้ามี)', null=True, verbose_name='Teams Webhook URL'),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='OutlookToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
