# Generated by Django 5.2.8 on 2025-12-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_equipment_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_user_seen',
            field=models.BooleanField(default=False, verbose_name='ผู้จองรับทราบแล้ว'),
        ),
    ]
