# Generated by Django 5.2.8 on 2025-12-09 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_booking_is_user_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='room',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvable_rooms', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติ'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='อาคาร/ตึก'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=1, verbose_name='ความจุ (คน)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='equipment_in_room',
            field=models.TextField(blank=True, help_text='ระบุอุปกรณ์ถาวรในห้อง', null=True, verbose_name='อุปกรณ์ถาวรในห้อง'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ชั้น'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='รูปภาพห้อง'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_maintenance',
            field=models.BooleanField(default=False, verbose_name='สถานะปิดปรับปรุง'),
        ),
        migrations.AlterField(
            model_name='room',
            name='line_notify_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Line Notify Token'),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='สถานที่ตั้ง'),
        ),
        migrations.AlterField(
            model_name='room',
            name='maintenance_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='สิ้นสุดปิดปรับปรุง'),
        ),
        migrations.AlterField(
            model_name='room',
            name='maintenance_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เริ่มปิดปรับปรุง'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อห้องประชุม'),
        ),
        migrations.AlterField(
            model_name='room',
            name='teams_webhook_url',
            field=models.TextField(blank=True, null=True, verbose_name='Teams Webhook URL'),
        ),
    ]
