# Generated by Django 5.2.8 on 2025-12-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_alter_equipment_description_alter_room_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='ต้องรออนุมัติ'),
        ),
    ]
