# Generated by Django 5.2.8 on 2025-12-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0039_room_requires_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_layout',
            field=models.CharField(choices=[('theatre', 'Theatre (เธียเตอร์)'), ('classroom', 'Classroom (แบบห้องเรียน)'), ('u_shape', 'U-Shape (รูปตัว U)'), ('banquet', 'Banquet (แบบจัดเลี้ยง)'), ('banquet_rounds', 'Banquet Rounds (โต๊ะจีน)'), ('conference', 'Conference (ห้องประชุมยาว)'), ('other', 'อื่นๆ (ระบุเพิ่มเติม)')], default='theatre', max_length=20, verbose_name='รูปแบบการจัดห้อง'),
        ),
    ]
