# Generated by Django 5.2.8 on 2025-12-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_booking_room_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='layout_attachment',
            field=models.FileField(blank=True, null=True, upload_to='layout_attachments/', verbose_name='ไฟล์แนบรูปแบบการจัดห้อง (กรณีเลือกอื่นๆ)'),
        ),
    ]
