# Generated by Django 5.2.8 on 2025-12-17 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_booking_layout_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='layout_attachment',
        ),
    ]
