# Generated by Django 5.2.8 on 2025-12-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_remove_booking_layout_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_layout_attachment',
            field=models.FileField(blank=True, null=True, upload_to='layout_attachments/', verbose_name='ไฟล์แนบรูปแบบการจัดห้อง (กรณีเลือกอื่นๆ)'),
        ),
    ]
