# Generated by Django 5.2.8 on 2025-12-23 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0043_booking_room_layout_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='แผนก'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='additional_notes',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='additional_requests',
            field=models.TextField(blank=True, null=True, verbose_name='คำขอเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='chairman',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ประธาน'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='แผนก'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(verbose_name='เวลาสิ้นสุด'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participant_count',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวนคน'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_in', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เข้าร่วม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='presentation_file',
            field=models.FileField(blank=True, null=True, upload_to='presentations/', verbose_name='ไฟล์นำเสนอ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_layout_attachment',
            field=models.FileField(blank=True, null=True, upload_to='layout_attachments/', verbose_name='ไฟล์แนบผังห้อง'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(verbose_name='เวลาเริ่ม'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(max_length=200, verbose_name='หัวข้อการประชุม'),
        ),
        migrations.AlterField(
            model_name='room',
            name='requires_approval',
            field=models.BooleanField(default=True, verbose_name='ต้องรออนุมัติ'),
        ),
    ]
