# Generated by Django 5.2.8 on 2025-12-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0045_alter_room_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์'),
        ),
    ]
