# Generated by Django 5.2.8 on 2025-12-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0047_alter_auditlog_options_remove_booking_parent_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='สถานะพร้อมใช้งาน'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='หมายเหตุสถานะ'),
        ),
    ]
