# Generated by Django 5.2.8 on 2026-01-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0049_alter_booking_room_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_layout',
            field=models.CharField(blank=True, choices=[('theatre', 'แบบเธียร์เตอร์ (Theatre)'), ('classroom', 'แบบห้องเรียน (Classroom)'), ('u_shape', 'แบบตัวยู (U-Shape)'), ('boardroom', 'แบบห้องประชุม (Conference)'), ('banquet', 'แบบจัดเลี้ยง (Banquet)'), ('banquet_rounds', 'แบบจัดเลี้ยงโต๊ะกลม (Banquet Rounds)'), ('other', 'อื่นๆ (ระบุในไฟล์แนบ)')], default='theatre', max_length=50),
        ),
    ]
