# Generated by Django 5.2.8 on 2026-01-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0050_alter_booking_room_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='presentation_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ลิงก์เอกสารประกอบ'),
        ),
    ]
