# Generated by Django 5.2.8 on 2026-01-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0051_booking_presentation_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='หมายเหตุสถานะ'),
        ),
    ]
