# Generated by Django 5.2.8 on 2026-01-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0052_room_status_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('general', 'ประชุมทั่วไป'), ('cleaning', 'แม่บ้านทำความสะอาด')], default='general', max_length=20, verbose_name='ประเภทการจอง'),
        ),
    ]
