# Generated by Django 5.2.8 on 2026-01-21 08:20

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0053_booking_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='presentation_file',
            field=models.FileField(blank=True, null=True, upload_to=booking.models.rename_file),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_layout_attachment',
            field=models.FileField(blank=True, null=True, upload_to=booking.models.rename_file),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=booking.models.rename_room_image),
        ),
    ]
