# Generated by Django 5.2.8 on 2026-01-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0054_alter_booking_presentation_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='แจ้งเตือนไลน์แล้ว'),
        ),
    ]
